### ISSUE TITLE
ListKit 2.0.0 for Cocoapods

### ISSUE THREAD

**Issue by michalciurus** [Ben-G/ListKit#9]
Hey, is there a chance you could update the Cocoapods repository with the latest version `2.0.0`, please? 

I'm writing a ReSwift step-by-step tutorial and I'd love my podfile to be as clean as possible.

Thanks! ✌️

**Comment by Ben-G** [comment]
@michalciurus Ups, didn't noticed I never pushed to CocoaPods trunk. Did now, thx for reporting this!
